<?php

namespace App\Models;

use App\Jobs\SendFeedbackToAdminJob;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Notifications\Notifiable;

/**
 * Class Feedback
 * @package App\Models
 * @property integer $id
 * @property string $feedback
 * @property integer $user_id
 * @property boolean $email_to_admin_sent
 */

class Feedback extends Model {
    use Notifiable;

    protected $table = "feedbacks";

    protected $guarded = ["id"];

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function(Feedback $feedback) {
            dispatch(new SendFeedbackToAdminJob($feedback));
        });
    }

    /**
     * @return BelongsTo
     */
    public function user() {
        return $this->belongsTo(User::class);
    }
}
